# Generated by Django 4.0.10 on 2023-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_alter_rsakeypair_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeodata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
    ]
