# Generated by Django 4.0.10 on 2023-05-21 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usergeodata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeoDataHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_geo_data_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Geo Data History',
                'verbose_name_plural': 'User Geo Data History',
            },
        ),
    ]
