# Generated by Django 4.0.10 on 2023-05-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('accounts', '0007_alter_usergeodata_id_alter_usergeodatahistory_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSessions',
            new_name='UserSession',
        ),
    ]
