version: '3'

volumes:
  playground_local_postgres_data: {}
  playground_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: playground_local_django
    container_name: playground_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: playground_production_postgres
    container_name: playground_local_postgres
    volumes:
      - playground_local_postgres_data:/var/lib/postgresql/data
      - playground_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: playground_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: playground_local_redis

  celeryworker:
    <<: *django
    image: playground_local_celeryworker
    container_name: playground_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: playground_local_celerybeat
    container_name: playground_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: playground_local_flower
    container_name: playground_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
